default:
    image: ubuntu:impish

variables:
    PACKAGE: "intellij-idea-community"
    TZ: UTC
    DEBIAN_FRONTEND: noninteractive

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - apt update && apt install -y git devscripts debhelper
    - export VERSION=$(git describe --abbrev=0 --tags | cut -d'v' -f2)
    - cd "$PACKAGE"_"$VERSION" || exit
    - debuild -us -uc
    - export PACKAGE_FILE="$PACKAGE"_"$VERSION"-1_all.deb
  artifacts:
    name: $PACKAGE_FILE
    paths:
        - ./*.deb
  rules:
    - if: $CI_COMMIT_TAG

deploy-job:
  stage: deploy
  script:
    - apt update && apt install -y git devscripts debhelper gnupg
    - export VERSION=$(git describe --abbrev=0 --tags | cut -d'v' -f2)
    - echo "$GPG_PRIVATE_KEY" | tr -d '\r' | gpg --import -
    - echo "$GPG_PUBLIC_KEY" | tr -d '\r' | gpg --import -
    - cd "$PACKAGE"_"$VERSION" || exit
    - debuild -S -k6D289F254B41A009B6AB5AC3122720F932D5CE46
    - cd ..
    - dput ppa:mmk2410/intellij-idea "$PACKAGE"_"$VERSION"-1_source.changes
  rules:
    - if: $CI_COMMIT_TAG

