default:
    image: ubuntu:impish

variables:
    PACKAGE: "intellij-idea-community"
    TZ: UTC
    DEBIAN_FRONTEND: noninteractive

stages:
  - build

build-job:
  stage: build
  script:
    - apt update && apt install -y git devscripts debhelper
    - export VERSION=$(git describe --abbrev=0 --tags | cut -d'v' -f2)
    - cd "$PACKAGE"_"$VERSION" || exit
    - debuild -us -uc
    - export PACKAGE_FILE="$PACKAGE"_"$VERSION"-1_all.deb
  artifacts:
    name: $PACKAGE_FILE
    paths:
        - ./*.deb
  rules:
    - if: $CI_COMMIT_TAG
